import { Verse as Verse_ } from './Verse.mjs';
import { AddedDocument } from './embed/AddedDocument.mjs';
export declare class Verse {
    id: string;
    rev: string | undefined;
    deletionDate: number | undefined;
    chapterName: string | undefined;
    paragraphName: string | undefined;
    verseSeq: number | undefined;
    startDate: number | undefined;
    createdTms: number | undefined;
    createdUserId: string | undefined;
    endDate: number | undefined;
    verseNum: number | undefined;
    verseSeqParent: number | undefined;
    verseLevel: number | undefined;
    verseType: string | undefined;
    checkBoxInd: string | undefined;
    minCheckNum: number | undefined;
    andClauseNum: number | undefined;
    textFr: string | undefined;
    textNl: string | undefined;
    requestType: string | undefined;
    agreementTerm: number | undefined;
    agreementTermUnit: string | undefined;
    maxPackageNumber: number | undefined;
    purchasingAdvisorQualList: string | undefined;
    legalReference: string | undefined;
    modificationDate: number | undefined;
    addedDocuments: Array<AddedDocument>;
    agreementYearMax: number | undefined;
    agreementRenewalMax: number | undefined;
    sexRestricted: string | undefined;
    minimumAgeAuthorized: number | undefined;
    maximumAgeAuthorized: number | undefined;
    maximumContentQuantity: number | undefined;
    maximumContentUnit: string | undefined;
    maximumStrengthQuantity: number | undefined;
    maximumStrengthUnit: string | undefined;
    maximumDurationQuantity: number | undefined;
    maximumDurationUnit: string | undefined;
    otherAddedDocumentInd: string | undefined;
    minimumAgeAuthorizedUnit: string | undefined;
    maximumAgeAuthorizedUnit: string | undefined;
    modificationStatus: string | undefined;
    children: Array<Verse_> | undefined;
    constructor(partial: Partial<Verse>);
}
