import { AmpStatus } from './AmpStatus.mjs';
import { AmppComponent } from './AmppComponent.mjs';
import { Atc } from './Atc.mjs';
import { Commercialization } from './Commercialization.mjs';
import { Company } from './Company.mjs';
import { DataPeriod } from './DataPeriod.mjs';
import { Dmpp } from './Dmpp.mjs';
import { Quantity } from './Quantity.mjs';
import { SamText } from './SamText.mjs';
import { SupplyProblem } from './SupplyProblem.mjs';
export declare class Ampp implements DataPeriod {
    from: number | undefined;
    to: number | undefined;
    index: number | undefined;
    ctiExtended: string | undefined;
    orphan: boolean;
    leafletLink: SamText | undefined;
    spcLink: SamText | undefined;
    rmaPatientLink: SamText | undefined;
    rmaProfessionalLink: SamText | undefined;
    parallelCircuit: number | undefined;
    parallelDistributor: string | undefined;
    packMultiplier: number | undefined;
    packAmount: Quantity | undefined;
    packDisplayValue: SamText | undefined;
    status: AmpStatus | undefined;
    atcs: Array<Atc>;
    crmLink: SamText | undefined;
    deliveryModusCode: string | undefined;
    deliveryModus: SamText | undefined;
    deliveryModusSpecificationCode: string | undefined;
    deliveryModusSpecification: SamText | undefined;
    dhpcLink: SamText | undefined;
    distributorCompany: Company | undefined;
    singleUse: boolean | undefined;
    speciallyRegulated: number | undefined;
    abbreviatedName: SamText | undefined;
    prescriptionName: SamText | undefined;
    note: SamText | undefined;
    posologyNote: SamText | undefined;
    noGenericPrescriptionReasons: Array<SamText> | undefined;
    exFactoryPrice: number | undefined;
    reimbursementCode: number | undefined;
    definedDailyDose: Quantity | undefined;
    officialExFactoryPrice: number | undefined;
    realExFactoryPrice: number | undefined;
    pricingInformationDecisionDate: number | undefined;
    components: Array<AmppComponent | undefined> | undefined;
    commercializations: Array<Commercialization> | undefined;
    supplyProblems: Array<SupplyProblem> | undefined;
    dmpps: Array<Dmpp>;
    vaccineIndicationCodes: Array<string> | undefined;
    rmaKeyMessages: SamText | undefined;
    genericPrescriptionRequired: boolean | undefined;
    constructor(partial: Partial<Ampp>);
}
