import { BoundedParameter } from './BoundedParameter.mjs';
import { Indication } from './Indication.mjs';
import { Quantity } from './Quantity.mjs';
import { RouteOfAdministration } from './RouteOfAdministration.mjs';
import { SamText } from './SamText.mjs';
export declare class StandardDosage {
    code: number | undefined;
    targetGroup: string | undefined;
    kidneyFailureClass: number | undefined;
    liverFailureClass: number | undefined;
    treatmentDurationType: string | undefined;
    temporalityDuration: Quantity | undefined;
    temporalityUserProvided: boolean | undefined;
    temporalityNote: SamText | undefined;
    quantity: number | undefined;
    quantityDenominator: number | undefined;
    quantityMultiplicator: string | undefined;
    quantityRangeLower: number | undefined;
    quantityRangeLowerDenominator: number | undefined;
    quantityRangeUpper: number | undefined;
    quantityRangeUpperDenominator: number | undefined;
    administrationFrequencyQuantity: number | undefined;
    administrationFrequencyIsMax: boolean | undefined;
    administrationFrequencyTimeframe: Quantity | undefined;
    maximumAdministrationQuantity: number | undefined;
    maximumAdministrationQuantityDenominator: number | undefined;
    maximumAdministrationQuantityMultiplicator: string | undefined;
    maximumDailyQuantity: number | undefined;
    maximumDailyQuantityDenominator: number | undefined;
    maximumDailyQuantityMultiplicator: string | undefined;
    textualDosage: SamText | undefined;
    supplementaryInfo: SamText | undefined;
    routeSpecification: SamText | undefined;
    indication: Array<Indication> | undefined;
    parameterBounds: Array<BoundedParameter> | undefined;
    routeOfAdministration: RouteOfAdministration | undefined;
    constructor(partial: Partial<StandardDosage>);
}
