steps:
  -   name: 'gcr.io/cloud-builders/git'
      entrypoint: 'bash'
      args: [ '-c', 'echo ${_DEPLOY} && git fetch --unshallow --tags && git checkout ${BRANCH_NAME} && git submodule init && git submodule update' ]

  -   name: 'docker'
      args: [ "build", "--build-arg", "REACT_APP_EXTERNAL_SERVICES_SPEC_ID=${_REACT_APP_EXTERNAL_SERVICES_SPEC_ID}", "--build-arg", "REACT_APP_EMAIL_AUTHENTICATION_PROCESS_ID=${_REACT_APP_EMAIL_AUTHENTICATION_PROCESS_ID}", "--build-arg", "REACT_APP_PARENT_ORGANISATION_ID=${_REACT_APP_PARENT_ORGANISATION_ID}","--build-arg", "REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY=${_REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY}", "-t", "docker.taktik.be/cardinal-sam-preventi-app", "." ]

  -   name: 'docker.taktik.be/cardinal-sam-preventi-app'
      entrypoint: sh
      args: [ '-c', 'cp -af /app/build /workspace' ]

  -   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args: ["gcloud", "storage", "rsync", "./build", "${_DEPLOY}", "--recursive", "--delete-unmatched-destination-objects", "--cache-control=no-cache"]

timeout: 1800s
